// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/api/v2/function.proto

package envoy_api_v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _function_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Function with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Function) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Uri

	// no validation rules for Subset

	// no validation rules for Timeout

	if v, ok := interface{}(m.GetGlimit()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FunctionValidationError{
				field:  "Glimit",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetBreakers()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FunctionValidationError{
				field:  "Breakers",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetDegrade()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FunctionValidationError{
				field:  "Degrade",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// FunctionValidationError is the validation error returned by
// Function.Validate if the designated constraints aren't met.
type FunctionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FunctionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FunctionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FunctionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FunctionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FunctionValidationError) ErrorName() string { return "FunctionValidationError" }

// Error satisfies the builtin error interface
func (e FunctionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFunction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FunctionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FunctionValidationError{}

// Validate checks the field values on TrafficLimit with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *TrafficLimit) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for WindowMils

	// no validation rules for BucketMils

	// no validation rules for Times

	return nil
}

// TrafficLimitValidationError is the validation error returned by
// TrafficLimit.Validate if the designated constraints aren't met.
type TrafficLimitValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrafficLimitValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrafficLimitValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrafficLimitValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrafficLimitValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrafficLimitValidationError) ErrorName() string { return "TrafficLimitValidationError" }

// Error satisfies the builtin error interface
func (e TrafficLimitValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrafficLimit.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrafficLimitValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrafficLimitValidationError{}

// Validate checks the field values on Downgrade with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Downgrade) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Enable

	// no validation rules for Body

	return nil
}

// DowngradeValidationError is the validation error returned by
// Downgrade.Validate if the designated constraints aren't met.
type DowngradeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DowngradeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DowngradeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DowngradeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DowngradeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DowngradeValidationError) ErrorName() string { return "DowngradeValidationError" }

// Error satisfies the builtin error interface
func (e DowngradeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDowngrade.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DowngradeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DowngradeValidationError{}
